#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model Pendulum
 Dymola Version 2023x, 2022-10-07 translated this at Fri Mar 24 19:17:04 2023

   */

#include <matrixop.h>
#include "matrixop.c"
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    2
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    1
#define NWP_   1
#define NP_    3
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1481817002
#define NHash2_ 1161132183
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    0
#define SizePre_ 0
#define SizeEq_ 1
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 1
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Pendulum";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/karlv/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#define QJacobianCGDef_ 1
DYMOLA_STATIC int QJacobianCG_[6]={1 , 2 , 1 , 2 , 0 , 0};
static int QJacobianGrp0[3]={2, 1, 0};
DYMOLA_STATIC struct QJacobianTag_ QJacobianGC2_[2]={
{0, QJacobianGrp0},{0,0}};
DYMOLA_STATIC double QJacobianCD_[3]={0  , 44 , 55};
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
InitialSection

InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
DYNX(W_,0) = DYNX(DP_,0)*sqr(DYNX(DP_,1));
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
 /* Linear system of equations to solve. */
/* Introducing 1 common subexpressions used in 0 expressions */
/* Of the common subexpressions 1 are reals, 0 are integers, and 0
   are booleans. */
DYNX(DYNhelp,0) = sin(DYNX(X_,0));
DYNX(F_,1) = RememberSimple_(DYNX(F_,1), 0);
SolveScalarLinearParametric(DYNX(W_,0),"J",  -DYNX(DP_,0)*DYNX(DP_,2)*
  DYNX(DP_,1)*DYNX(DYNhelp,0)," -m*g*L*sin(phi)", DYNX(F_,1),"der(w)");
 /* End of Equation Block */ 

DYNX(F_,0) = DYNX(X_,1);

AcceptedSection1

AcceptedSection2

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("m", "Mass of pendulum [kg]", 0, 1, 0.0,1E+100,0.0,0,560)
DeclareParameter("L", "Length of pendulum [m]", 1, 1, 0.0,0.0,0.0,0,560)
DeclareParameter("g", "[m/s2]", 2, 9.81, 0.0,0.0,0.0,0,560)
DeclareVariable("J", "Moment of inertia [kg.m2]", 0, 0.0, 0.0,0.0,0.0,0,513)
DeclareState("phi", "Pendulum angle [rad|deg]", 0, 0.1, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(phi)", "der(Pendulum angle) [rad/s]", 0, 0.0, 0.0,0.0,0.0,\
0,512)
DeclareState("w", "[rad/s]", 1, 0.0, 0.0,0.0,0.0,0,560)
DeclareDerivative("der(w)", "[rad/s2]", 1, 0.0, 0.0,0.0,0.0,0,512)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(F_,1), 0.0, 0);
EndEqBlock
EndDataBlock
