#define DYNEventSpecial
/* DSblock model generated by Dymola from Modelica model Tutorial.AdvancedModelica.Replaceable.Examples.SpringInertia
 Dymola Version 2023x, 2022-10-07 translated this at Fri Mar 31 19:30:57 2023

   */

#include <matrixop.h>
#include "matrixop.c"
#if defined(DynSimStruct)
static double DymArrays0[3]={3.0, 0.0001, 4.0};
#endif
/* Declaration of C-structs */
/* Prototypes for functions used in model */
/* Codes used in model */
/* DSblock C-code: */

#define NX_    4
#define NX2_   0
#define NU_    0
#define NY_    0
#define NW_    21
#define NWP_   9
#define NP_    9
#define NPS_   0
#define ND_   0
#define NXP_   0
#define NInitial_   0
#define MAXAuxStr_   0
#define MAXAuxStrLen_   500
#define NHash1_ 1265021852
#define NHash2_ -1687143195
#define NHash3_ 0
#define NI_    0
#define NRelF_ 0
#define NRel_  0
#define NTim_  0
#define NSamp_ 0
#define NCons_ 0
#define NA_    25
#define SizePre_ 0
#define SizeEq_ 2
#define SizeDelay_ 0
#define QNLmax_ 0
#define MAXAux 0
#define NrDymolaTimers_ 0
#define NWhen_ 0
#define NCheckIf_ 0
#define NGlobalHelp_ 0
#define NGlobalHelpI_ 0
#ifndef NExternalObject_
#define NExternalObject_ 0
#endif
#include <moutil.c>
DYMOLA_STATIC unsigned int FMIClockValueReferences_[1]={0};
DYMOLA_STATIC unsigned int FMIClockFirstValueReferences_[1]={0};
PreNonAliasDef(0)
PreNonAliasDef(1)
PreNonAliasDef(2)
PreNonAliasDef(3)
PreNonAliasDef(4)
PreNonAliasDef(5)
#if !defined(DYM2CCUR)
 DYMOLA_STATIC const char*modelName="Tutorial.AdvancedModelica.Replaceable.Examples.SpringInertia";
#endif
DYMOLA_STATIC const char*usedLibraries[]={0};
DYMOLA_STATIC const char*dllLibraryPath[]={0};
DYMOLA_STATIC const char*default_dymosim_license_filename=
 "c:/users/karlv/appdata/roaming/dassaultsystemes/dymola/dymola.lic";
#include <dsblock1.c>

/* Define variable names. */

#define Sections_

TranslatedEquations
InitialSection
#if defined(DynSimStruct)
DYNX(F_,1) = 0;
DYNX(F_,3) = 0;
#endif

InitialSection
#if defined(DynSimStruct)
memcpy(&DYNX(W_,0), &DymArrays0, sizeof(double)*3);
DYNX(W_,3) = false;
memcpy(&DYNX(W_,5), &DymArrays0, sizeof(double)*3);
DYNX(W_,8) = false;
DYNX(W_,4) = 0.0;
#endif
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
BoundParameterSection
InitialSection
InitialStartSection
InitialSection
if (!DymolaUserHomotopy) UpdateInitVars(time, X_, XD_, U_, DP_, IP_, LP_, F_, Y_, W_, QZ_, duser_, iuser_, cuser_, did_, 1);
DefaultSection
InitializeData(0)
InitialSection
InitialSectionB
Init_=false;InitializeData(2);Init_=true;
EndInitialSection

OutputSection

DynamicsSection
DYNX(W_,19) = DYNX(DP_,6)*(DYNX(X_,2)-DYNX(DP_,8));
DYNX(W_,20) = DYNX(DP_,7)*DYNX(X_,3);
DYNX(W_,10) = DYNX(W_,19)+DYNX(W_,20);
 /* Linear system of equations to solve. */
DYNX(W_,17) = RememberSimple_(DYNX(W_,17), 0);
SolveScalarLinearParametric(DYNX(DP_,5),"inertia2.J",  -DYNX(W_,10),
  "inertia2.flange_a.tau", DYNX(W_,17),"der(inertia2.w)");
 /* End of Equation Block */ 

DYNX(W_,13) = DYNX(DP_,2)*(DYNX(X_,0)-DYNX(DP_,4));
DYNX(W_,14) = DYNX(DP_,3)*DYNX(X_,1);
DYNX(W_,9) = DYNX(W_,13)+DYNX(W_,14);
 /* Linear system of equations to solve. */
DYNX(F_,1) = RememberSimple_(DYNX(F_,1), 1);
SolveScalarLinearParametric(DYNX(DP_,1),"inertia1.J", DYNX(W_,10)-DYNX(W_,9),
  "inertia1.flange_b.tau-( -inertia1.flange_a.tau)", DYNX(F_,1),"der(springDamper1.w_rel)");
 /* End of Equation Block */ 

DYNX(F_,3) = DYNX(W_,17)-DYNX(F_,1);
DYNX(F_,2) = DYNX(X_,3);
DYNX(F_,0) = DYNX(X_,1);

AcceptedSection1

AcceptedSection2
DYNX(W_,11) = DYNX(X_,0)+DYNX(DP_,0);
DYNX(W_,15) = DYNX(X_,2)+DYNX(W_,11);
DYNX(W_,16) = DYNX(X_,3)+DYNX(X_,1);
DYNX(W_,12) = DYNX(W_,14)*DYNX(X_,1);
DYNX(W_,18) = DYNX(W_,20)*DYNX(X_,3);

DefaultSection
InitializeData(1)
EndTranslatedEquations

#include <dsblock6.c>

PreNonAliasNew(0)
StartNonAlias(0)
DeclareParameter("fixed.phi0", "Fixed offset angle of housing [rad|deg]", 0, 0, \
0.0,0.0,0.0,0,560)
DeclareAlias2("fixed.flange.phi", "Absolute rotation angle of flange [rad|deg]",\
 "fixed.phi0", 1, 7, 0, 4)
DeclareVariable("fixed.flange.tau", "Cut torque in the flange [N.m]", 9, 0.0, \
0.0,0.0,0.0,0,776)
DeclareAlias2("inertia1.flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "inertia1.phi", 1, 5, 11, 4)
DeclareAlias2("inertia1.flange_a.tau", "Cut torque in the flange [N.m]", \
"fixed.flange.tau", -1, 5, 9, 132)
DeclareAlias2("inertia1.flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "inertia1.phi", 1, 5, 11, 4)
DeclareVariable("inertia1.flange_b.tau", "Cut torque in the flange [N.m]", 10, \
0.0, 0.0,0.0,0.0,0,776)
DeclareParameter("inertia1.J", "Moment of inertia [kg.m2]", 1, 1, 0.0,1E+100,0.0,\
0,560)
DeclareVariable("inertia1.stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 0, 3, 1.0,5.0,0.0,0,1541)
DeclareVariable("inertia1.phi", "Absolute rotation angle of component [rad|deg]",\
 11, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("inertia1.der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 "springDamper1.w_rel", 1, 1, 1, 0)
DeclareAlias2("inertia1.w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 "springDamper1.w_rel", 1, 1, 1, 0)
DeclareAlias2("inertia1.der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 "springDamper1.der(w_rel)", 1, 6, 1, 0)
DeclareAlias2("inertia1.a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "springDamper1.der(w_rel)", 1, 6, 1, 0)
DeclareParameter("springDamper1.c", "Spring constant [N.m/rad]", 2, 1000, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("springDamper1.d", "Damping constant [N.m.s/rad]", 3, 10, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("springDamper1.phi_rel0", "Unstretched spring angle [rad|deg]",\
 4, 0, 0.0,0.0,0.0,0,560)
DeclareState("springDamper1.phi_rel", "Relative rotation angle (= flange_b.phi - flange_a.phi) [rad|deg]",\
 0, 0, 0.0,0.0,0.0001,0,560)
DeclareDerivative("springDamper1.der(phi_rel)", "der(Relative rotation angle (= flange_b.phi - flange_a.phi)) [rad/s]",\
 0, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("springDamper1.w_rel", "Relative angular velocity (= der(phi_rel)) [rad/s]",\
 1, 10, 0.0,0.0,0.0,0,560)
DeclareDerivative("springDamper1.der(w_rel)", "der(Relative angular velocity (= der(phi_rel))) [rad/s2]",\
 1, 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("springDamper1.a_rel", "Relative angular acceleration (= der(w_rel)) [rad/s2]",\
 "springDamper1.der(w_rel)", 1, 6, 1, 0)
DeclareAlias2("springDamper1.tau", "Torque between flanges (= flange_b.tau) [N.m]",\
 "fixed.flange.tau", 1, 5, 9, 0)
DeclareAlias2("springDamper1.flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "fixed.phi0", 1, 7, 0, 4)
DeclareAlias2("springDamper1.flange_a.tau", "Cut torque in the flange [N.m]", \
"fixed.flange.tau", -1, 5, 9, 132)
DeclareAlias2("springDamper1.flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "inertia1.phi", 1, 5, 11, 4)
DeclareAlias2("springDamper1.flange_b.tau", "Cut torque in the flange [N.m]", \
"fixed.flange.tau", 1, 5, 9, 132)
DeclareVariable("springDamper1.phi_nominal", "Nominal value of phi_rel (used for scaling) [rad|rad]",\
 1, 0.0001, 0.0,1E+100,0.0,0,513)
DeclareVariable("springDamper1.stateSelect", "Priority to use phi_rel and w_rel as states [:#(type=StateSelect)]",\
 2, 4, 1.0,5.0,0.0,0,1541)
DeclareVariable("springDamper1.useHeatPort", "= true, if heatPort is enabled [:#(type=Boolean)]",\
 3, false, 0.0,0.0,0.0,0,1539)
DeclareVariable("springDamper1.lossPower", "Loss power leaving component via heatPort (> 0, if heat is flowing out of component) [W]",\
 12, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("springDamper1.tau_c", "Spring torque [N.m]", 13, 0.0, 0.0,0.0,\
0.0,0,2560)
DeclareVariable("springDamper1.tau_d", "Damping torque [N.m]", 14, 0.0, 0.0,0.0,\
0.0,0,2560)
DeclareAlias2("inertia2.flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "inertia2.phi", 1, 5, 15, 4)
DeclareAlias2("inertia2.flange_a.tau", "Cut torque in the flange [N.m]", \
"inertia1.flange_b.tau", -1, 5, 10, 132)
DeclareAlias2("inertia2.flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "inertia2.phi", 1, 5, 15, 4)
DeclareVariable("inertia2.flange_b.tau", "Cut torque in the flange [N.m]", 4, \
0.0, 0.0,0.0,0.0,0,777)
DeclareParameter("inertia2.J", "Moment of inertia [kg.m2]", 5, 1, 0.0,1E+100,0.0,\
0,560)
DeclareVariable("inertia2.stateSelect", "Priority to use phi and w as states [:#(type=StateSelect)]",\
 5, 3, 1.0,5.0,0.0,0,1541)
DeclareVariable("inertia2.phi", "Absolute rotation angle of component [rad|deg]",\
 15, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("inertia2.der(phi)", "der(Absolute rotation angle of component) [rad/s]",\
 "inertia2.w", 1, 5, 16, 0)
DeclareVariable("inertia2.w", "Absolute angular velocity of component (= der(phi)) [rad/s]",\
 16, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("inertia2.der(w)", "der(Absolute angular velocity of component (= der(phi))) [rad/s2]",\
 17, 0.0, 0.0,0.0,0.0,0,512)
DeclareAlias2("inertia2.a", "Absolute angular acceleration of component (= der(w)) [rad/s2]",\
 "inertia2.der(w)", 1, 5, 17, 0)
DeclareParameter("springDamper2.c", "Spring constant [N.m/rad]", 6, 100, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("springDamper2.d", "Damping constant [N.m.s/rad]", 7, 1, 0.0,\
1E+100,0.0,0,560)
DeclareParameter("springDamper2.phi_rel0", "Unstretched spring angle [rad|deg]",\
 8, 0, 0.0,0.0,0.0,0,560)
DeclareState("springDamper2.phi_rel", "Relative rotation angle (= flange_b.phi - flange_a.phi) [rad|deg]",\
 2, 0, 0.0,0.0,0.0001,0,560)
DeclareDerivative("springDamper2.der(phi_rel)", "der(Relative rotation angle (= flange_b.phi - flange_a.phi)) [rad/s]",\
 2, 0.0, 0.0,0.0,0.0,0,512)
DeclareState("springDamper2.w_rel", "Relative angular velocity (= der(phi_rel)) [rad/s]",\
 3, 0, 0.0,0.0,0.0,0,560)
DeclareDerivative("springDamper2.der(w_rel)", "der(Relative angular velocity (= der(phi_rel))) [rad/s2]",\
 3, 0, 0.0,0.0,0.0,0,512)
DeclareAlias2("springDamper2.a_rel", "Relative angular acceleration (= der(w_rel)) [rad/s2]",\
 "springDamper2.der(w_rel)", 1, 6, 3, 0)
DeclareAlias2("springDamper2.tau", "Torque between flanges (= flange_b.tau) [N.m]",\
 "inertia1.flange_b.tau", 1, 5, 10, 0)
DeclareAlias2("springDamper2.flange_a.phi", "Absolute rotation angle of flange [rad|deg]",\
 "inertia1.phi", 1, 5, 11, 4)
DeclareAlias2("springDamper2.flange_a.tau", "Cut torque in the flange [N.m]", \
"inertia1.flange_b.tau", -1, 5, 10, 132)
DeclareAlias2("springDamper2.flange_b.phi", "Absolute rotation angle of flange [rad|deg]",\
 "inertia2.phi", 1, 5, 15, 4)
DeclareAlias2("springDamper2.flange_b.tau", "Cut torque in the flange [N.m]", \
"inertia1.flange_b.tau", 1, 5, 10, 132)
DeclareVariable("springDamper2.phi_nominal", "Nominal value of phi_rel (used for scaling) [rad|rad]",\
 6, 0.0001, 0.0,1E+100,0.0,0,513)
DeclareVariable("springDamper2.stateSelect", "Priority to use phi_rel and w_rel as states [:#(type=StateSelect)]",\
 7, 4, 1.0,5.0,0.0,0,1541)
DeclareVariable("springDamper2.useHeatPort", "= true, if heatPort is enabled [:#(type=Boolean)]",\
 8, false, 0.0,0.0,0.0,0,1539)
DeclareVariable("springDamper2.lossPower", "Loss power leaving component via heatPort (> 0, if heat is flowing out of component) [W]",\
 18, 0.0, 0.0,0.0,0.0,0,512)
DeclareVariable("springDamper2.tau_c", "Spring torque [N.m]", 19, 0.0, 0.0,0.0,\
0.0,0,2560)
DeclareVariable("springDamper2.tau_d", "Damping torque [N.m]", 20, 0.0, 0.0,0.0,\
0.0,0,2560)
EndNonAlias(0)

#define DymolaHaveUpdateInitVars 1
#include <dsblock5.c>

DYMOLA_STATIC void UpdateInitVars(double*time, double* X_, double* XD_, double* U_, double* DP_, int IP_[], Dymola_bool LP_[], double* F_, double* Y_, double* W_, double QZ_[], double duser_[], int iuser_[], void*cuser_[],struct DYNInstanceData*did_,int initialCall) {
}
StartDataBlock
StartEqBlock
DoRemember_(DYNX(W_,17), 0.0, 0);
DoRemember_(DYNX(F_,1), 0, 1);
EndEqBlock
EndDataBlock
